### ISSUE TITLE
Incorrect preview than FB/LinkedIn

### ISSUE THREAD

**Issue by tonyxu-io** [MichaelYuhe/open-graph-checker#1]
Thank you for making this tool and open source it. This is super cool!

I'm testing my blog using your tool and found that it renders differently than LinkedIn/Facebook.

This is the facebook debug link: https://developers.facebook.com/tools/debug/?q=tonyxu.io

You can compare it with your tool using `tonyxu.io`.

**Comment by MichaelYuhe** [comment]
Thanks for the feedback, I don't use LinkedIn and Facebook so I just get the preview template from a og check website! I'll take a look today and fix it

**Comment by MichaelYuhe** [comment]
Fixed

**Comment by tonyxu-io** [comment]
Thanks for the quick fix! Appreciate it!
